# Primary lib and include dir

if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(LIB_PREFIX "lib")
    set(LIB_SUFFIX ".a")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(LIB_PREFIX "")
    set(LIB_SUFFIX ".lib")
endif()

set(PYEXT_ROOT_DIR ${PYEXT_VENDOR_DIR} CACHE PATH "")
set(PYEXT_LIB_DIR "${PYEXT_ROOT_DIR}/lib")

set(PYEXT_INCLUDE_DIR "${PYEXT_ROOT_DIR}/include")
set(PYEXT_INCLUDE_DIRS ${PYEXT_INCLUDE_DIR})

set(PYEXT_LIBRARY "${PYEXT_LIB_DIR}/${LIB_PREFIX}pyext${LIB_SUFFIX}")
set(PYEXT_LIBRARIES ${PYEXT_LIBRARY})

set(PYEXT_FOUND TRUE)


# Sub-targets

add_library(pyext::pyext UNKNOWN IMPORTED)
set_target_properties(pyext::pyext PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${PYEXT_INCLUDE_DIRS}"
    IMPORTED_LOCATION "${PYEXT_LIB_DIR}/${LIB_PREFIX}pyext${LIB_SUFFIX}"
)
